dotfiles_dir = ".dotfiles"

[settings]
vars = ["vars.toml"]
posthooks = [
  "systemctl --user daemon-reload",
  "systemctl --user enable awww.service awww-overview.service",
]

[settings.dots]
fzf = { source = "terminal/fzf", target = ".config/fzf", direct = true }
zsh = { source = "terminal/zsh/zshrc", target = ".zshrc", direct = true }
starship = { source = "terminal/starship.toml", target = ".config/starship.toml", direct = true }
neovim = { source = "nvim", target = ".config/nvim", direct = true }
git = { source = "git/gitconfig", target = ".gitconfig" }
dms = { source = "dms", target = ".config/DankMaterialShell", direct = true }
lazygit = { source = "git/lazygit", target = ".config/lazygit", direct = true }
niri = { source = "niri", target = ".config/niri", direct = true }
awww = { source = "awww/awww.service", target = ".config/systemd/user/awww.service", direct = true }
awww_overview = { source = "awww/awww-overview.service", target = ".config/systemd/user/awww-overview.service", direct = true }
ghostty = { source = "terminal/ghostty", target = ".config/ghostty", direct = true }
btop = { source = "terminal/btop", target = ".config/btop", direct = true }
fastfetch = { source = "terminal/fastfetch", target = ".config/fastfetch", direct = true }
paru = { source = "paru/paru.conf", target = ".config/paru/paru.conf", direct = true }
xdg = { source = "xdg/user-dirs.dirs", target = ".config/user-dirs.dirs", direct = true }
xdg_conf = { source = "xdg/user-dirs.conf", target = ".config/user-dirs.conf", direct = true }
fontconfig = { source = "fontconfig", target = ".config/fontconfig", direct = true }

