device_name = "RONGYUAN 2.4G Wireless Device"
phys = "usb-0000:00:14.0-5.4/input2"

[[remap]]
input = ["KEY_LEFTALT", "KEY_H"]
output = ["KEY_LEFT"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_J"]
output = ["KEY_DOWN"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_K"]
output = ["KEY_UP"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_L"]
output = ["KEY_RIGHT"]

[[remap]]
input = ["KEY_RIGHTALT", "KEY_C"]
output = ["KEY_RIGHTALT", "KEY_COMMA"]

[[remap]]
input = ["KEY_LEFTSHIFT", "KEY_GRAVE"]
output = ["KEY_LEFTSHIFT", "KEY_RIGHTALT", "KEY_GRAVE"]

[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]
