add_newline = true

format = """
[╭─ ](bold blue)$username$hostname$directory$python$git_branch$git_commit$git_state$git_metrics$git_status$fill$cmd_duration
[╰─ \\$](bold blue) """

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname](bold green) "
disabled = false

[directory]
truncate_to_repo = false
style = "bold blue"
truncation_symbol = ".../"
truncation_length = 5

[python]
format = '[(\($virtualenv\))]($style)'
style = "bold blue"

[package]
disabled = true

[fill]
symbol = " "

[cmd_duration]
min_time = 0
format = "[$duration](cyan)"
